name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v6

      - name: Basic check
        run: echo "PR check passed"
